[env]
TERM = "xterm-256color"

[window]
opacity = 0.85
padding.x = 10
padding.y = 10
decorations = "Buttonless"
dynamic_title = true

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 10.0

[colors.primary]
background = "#011423"
foreground = "#cbe0f0"

[colors.cursor]
text = "#011423"
cursor = "#65b2ff"

[colors.selection]
text = "#cbe0f0"
background = "#1f3b5c"

[colors.normal]
black = "#100e23"
red = "#ff5458"
green = "#62d196"
yellow = "#ffb378"
blue = "#65b2ff"
magenta = "#906cff"
cyan = "#63f2f1"
white = "#cbe3e7"

[colors.bright]
black = "#565575"
red = "#ff8080"
green = "#95ffa4"
yellow = "#ffe9aa"
blue = "#91ddff"
magenta = "#c991e1"
cyan = "#aaffe4"
white = "#e8fafc"

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
blink_timeout = 15
unfocused_hollow = true
thickness = 0.15

[scrolling]
history = 10000
multiplier = 3

[[keyboard.bindings]]
key = "Backspace"
mods = "Control"
chars = "\u001b[127;5u"

[[keyboard.bindings]]
key = "Backspace"
mods = "Alt"
chars = "\u001b[127;3u"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`||:'' ()[]{}<>"
save_to_clipboard = true

[general]
live_config_reload = true
