# Hyprpaper config
# Fallback wallpaper - slideshow will override this

wallpaper {
    monitor =
    path = ~/.config/backgrounds/ali-liston.jpg
    fit_mode = cover
}

splash = true
splash_offset = 64
