# Window Rules
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more info

# Examples (disabled)
# windowrule = float,^(kitty)$
# windowrulev2 = opacity 0.8 0.8,class:^(kitty)$

# Mullvad VPN - always floating
windowrule = match:class mullvad-vpn float
windowrule = match:class mullvad-vpn move 69.5% 55%
windowrule = match:class mullvad-vpn size 30% 40%

# Brave Browser
windowrule = match:class Brave-browser tile

# Thunar file manager
windowrule = match:class thunar float
windowrule = match:class thunar center
windowrule = match:class thunar size 50% 50%

# Badlion Client
windowrule = match:class BadlionClient float
windowrule = match:class BadlionClient center
windowrule = match:class BadlionClient size 50% 50%

# Discord
windowrule = match:initial_title discord float
windowrule = match:initial_title discord center
windowrule = match:initial_title discord size 50% 50%
windowrule = match:initial_title discord monitor DP-2

# Brave Google login popup
windowrule = match:initial_title "Untitled - Brave" float
windowrule = match:initial_title "Untitled - Brave" center
windowrule = match:initial_title "Untitled - Brave" size 50% 50%

# Pavucontrol (audio control)
windowrule = match:class pavucontrol float
windowrule = match:class pavucontrol move 69.5% 55%
windowrule = match:class pavucontrol size 30% 40%


# Layer rules

layerrule = blur on,match:namespace logout_dialog

# Other layer rules (disabled)
# layerrule = blur,waybar
# layerrule = blur,wofi


# Smart gaps (disabled)
# workspace = w[tv1], gapsout:0, gapsin:0
# windowrule = border_size 0, match:float 0, match:workspace w[tv1]

# Workspace assignments (disabled)
# workspace = 1, monitor:HMDI-A-1
# workspace = 2, monitor:DP-1
